<hr>

# 🤖 STREAMLIT 🤖

<style>
h1 {
    text-align: center;
    color: hotpink;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<hr>

## Read the preprocessed data

In [35]:
import pandas as pd
import numpy as np

In [36]:
X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")   
y_train = pd.read_csv("../data/processed/y_train.csv")
y_test = pd.read_csv("../data/processed/y_test.csv")

In [37]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(9864, 74)
(2466, 74)
(9864, 1)
(2466, 1)

In [38]:
X_train.head()

,admin,admin_duration,info,info_duration,prod_related,prod_related_duration,bounce_rate,exit_rate,page_value,special_day,weekend,month_Aug,month_Dec,month_Feb,month_Jul,month_June,month_Mar,month_May,month_Nov,month_Oct,month_Sep,visitor_type_New_Visitor,visitor_type_Other,visitor_type_Returning_Visitor,os_1,os_2,os_3,os_4,os_5,os_6,os_7,os_8,browser_1,browser_2,browser_3,browser_4,browser_5,browser_6,browser_7,browser_8,browser_9,browser_10,browser_11,browser_12,browser_13,region_1,region_2,region_3,region_4,region_5,region_6,region_7,region_8,region_9,traffic_type_1,traffic_type_2,traffic_type_3,traffic_type_4,traffic_type_5,traffic_type_6,traffic_type_7,traffic_type_8,traffic_type_9,traffic_type_10,traffic_type_11,traffic_type_12,traffic_type_13,traffic_type_14,traffic_type_15,traffic_type_16,traffic_type_17,traffic_type_18,traffic_type_19,traffic_type_20
0,8,732.25,0,0.0,34,1345.755952,0.005128,0.013342,12.274195,0.8,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.00,0,0.0,4,157.200000,0.040000,0.100000,0.000000,0.0,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0.00,0,0.0,4,42.000000,0.000000,0.050000,0.000000,0.0,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,338.00,0,0.0,17,1205.566667,0.012500,0.037500,19.236250,0.8,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0.00,0,0.0,32,827.646212,0.000000,0.000587,54.676348,0.0,False,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
X_train.columns

Index(['admin', 'admin_duration', 'info', 'info_duration', 'prod_related',
       'prod_related_duration', 'bounce_rate', 'exit_rate', 'page_value',
       'special_day', 'weekend', 'month_Aug', 'month_Dec', 'month_Feb',
       'month_Jul', 'month_June', 'month_Mar', 'month_May', 'month_Nov',
       'month_Oct', 'month_Sep', 'visitor_type_New_Visitor',
       'visitor_type_Other', 'visitor_type_Returning_Visitor', 'os_1', 'os_2',
       'os_3', 'os_4', 'os_5', 'os_6', 'os_7', 'os_8', 'browser_1',
       'browser_2', 'browser_3', 'browser_4', 'browser_5', 'browser_6',
       'browser_7', 'browser_8', 'browser_9', 'browser_10', 'browser_11',
       'browser_12', 'browser_13', 'region_1', 'region_2', 'region_3',
       'region_4', 'region_5', 'region_6', 'region_7', 'region_8', 'region_9',
       'traffic_type_1', 'traffic_type_2', 'traffic_type_3', 'traffic_type_4',
       'traffic_type_5', 'traffic_type_6', 'traffic_type_7', 'traffic_type_8',
       'traffic_type_9', 'traffic_type_10', 'traffic_type_11',
       'traffic_type_12', 'traffic_type_13', 'traffic_type_14',
       'traffic_type_15', 'traffic_type_16', 'traffic_type_17',
       'traffic_type_18', 'traffic_type_19', 'traffic_type_20'],
      dtype='object')

In [40]:
X_train.describe()

,admin,admin_duration,info,info_duration,prod_related,prod_related_duration,bounce_rate,exit_rate,page_value,special_day,month_Aug,month_Dec,month_Feb,month_Jul,month_June,month_Mar,month_May,month_Nov,month_Oct,month_Sep,visitor_type_New_Visitor,visitor_type_Other,visitor_type_Returning_Visitor,os_1,os_2,os_3,os_4,os_5,os_6,os_7,os_8,browser_1,browser_2,browser_3,browser_4,browser_5,browser_6,browser_7,browser_8,browser_9,browser_10,browser_11,browser_12,browser_13,region_1,region_2,region_3,region_4,region_5,region_6,region_7,region_8,region_9,traffic_type_1,traffic_type_2,traffic_type_3,traffic_type_4,traffic_type_5,traffic_type_6,traffic_type_7,traffic_type_8,traffic_type_9,traffic_type_10,traffic_type_11,traffic_type_12,traffic_type_13,traffic_type_14,traffic_type_15,traffic_type_16,traffic_type_17,traffic_type_18,traffic_type_19,traffic_type_20
count,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000,9864.000000
mean,2.317620,81.241059,0.504663,34.590252,31.452758,1186.546010,0.022396,0.043313,5.944562,0.062693,0.034672,0.141018,0.014801,0.034874,0.023114,0.155921,0.274027,0.239254,0.045012,0.037307,0.136557,0.007502,0.855941,0.209144,0.534773,0.207826,0.038828,0.000507,0.001723,0.000406,0.006792,0.198601,0.644870,0.008414,0.060422,0.038727,0.014193,0.003650,0.010848,0.000101,0.013686,0.000507,0.000710,0.005272,0.383414,0.093674,0.197790,0.094992,0.027474,0.065187,0.061436,0.034165,0.041869,0.196067,0.317822,0.167680,0.087794,0.021796,0.035483,0.003548,0.027170,0.003345,0.037510,0.019769,0.000101,0.058901,0.001217,0.003345,0.000304,0.000101,0.000912,0.001318,0.015815
std,3.319144,179.610421,1.275169,141.428972,43.615440,1909.252291,0.048809,0.048901,18.562169,0.201271,0.182956,0.348058,0.120763,0.183471,0.150274,0.362798,0.446045,0.426650,0.207341,0.189524,0.343397,0.086293,0.351168,0.406718,0.498815,0.405772,0.193195,0.022510,0.041481,0.020134,0.082140,0.398967,0.478577,0.091348,0.238279,0.192953,0.118292,0.060305,0.103590,0.010069,0.116190,0.022510,0.026631,0.072418,0.486243,0.291389,0.398353,0.293219,0.163467,0.246867,0.240140,0.181661,0.200301,0.397040,0.465654,0.373601,0.283009,0.146026,0.185005,0.059464,0.162585,0.057746,0.190018,0.139212,0.010069,0.235451,0.034860,0.057746,0.017438,0.010069,0.030194,0.036281,0.124766
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,182.566071,0.000000,0.014286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,8.000000,0.000000,0.000000,18.000000,600.536667,0.003110,0.025195,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,4.000000,93.000000,0.000000,0.000000,38.000000,1474.508333,0.017081,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [41]:
X_test.describe()

,admin,admin_duration,info,info_duration,prod_related,prod_related_duration,bounce_rate,exit_rate,page_value,special_day,month_Aug,month_Dec,month_Feb,month_Jul,month_June,month_Mar,month_May,month_Nov,month_Oct,month_Sep,visitor_type_New_Visitor,visitor_type_Other,visitor_type_Returning_Visitor,os_1,os_2,os_3,os_4,os_5,os_6,os_7,os_8,browser_1,browser_2,browser_3,browser_4,browser_5,browser_6,browser_7,browser_8,browser_9,browser_10,browser_11,browser_12,browser_13,region_1,region_2,region_3,region_4,region_5,region_6,region_7,region_8,region_9,traffic_type_1,traffic_type_2,traffic_type_3,traffic_type_4,traffic_type_5,traffic_type_6,traffic_type_7,traffic_type_8,traffic_type_9,traffic_type_10,traffic_type_11,traffic_type_12,traffic_type_13,traffic_type_14,traffic_type_15,traffic_type_16,traffic_type_17,traffic_type_18,traffic_type_19,traffic_type_20
count,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.00000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.0,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.0,2466.000000,2466.000000,2466.000000,2466.0,2466.0,2466.000000,2466.000000,2466.000000
mean,2.305353,79.128815,0.499189,34.000983,32.846310,1227.547061,0.021375,0.042111,5.668042,0.056367,0.036902,0.136253,0.01541,0.035685,0.024331,0.149635,0.268045,0.258719,0.042579,0.032441,0.140714,0.004461,0.854826,0.211679,0.537713,0.204785,0.038524,0.000406,0.000811,0.001217,0.004866,0.203974,0.648824,0.008921,0.056772,0.034469,0.013788,0.005272,0.011354,0.0,0.011354,0.000406,0.001217,0.003650,0.404704,0.085969,0.183293,0.099351,0.019059,0.065693,0.062855,0.039335,0.039740,0.209651,0.315491,0.161395,0.082320,0.018248,0.038118,0.002028,0.030414,0.003650,0.032441,0.021087,0.0,0.063666,0.000406,0.002028,0.0,0.0,0.000406,0.001622,0.017032
std,3.332979,164.992517,1.250152,138.024375,47.754225,1931.277884,0.047185,0.047355,18.595609,0.189164,0.188559,0.343127,0.12320,0.185542,0.154106,0.356786,0.443031,0.438019,0.201947,0.177205,0.347797,0.066653,0.352348,0.408581,0.498677,0.403626,0.192496,0.020137,0.028473,0.034865,0.069602,0.403032,0.477435,0.094050,0.231454,0.182467,0.116632,0.072429,0.105972,0.0,0.105972,0.020137,0.034865,0.060314,0.490934,0.280375,0.386985,0.299194,0.136761,0.247796,0.242751,0.194430,0.195388,0.407142,0.464805,0.367969,0.274907,0.133875,0.191521,0.044992,0.171757,0.060314,0.177205,0.143703,0.0,0.244206,0.020137,0.044992,0.0,0.0,0.020137,0.040250,0.129415
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,190.627083,0.000000,0.014286,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
50%,1.000000,6.500000,0.000000,0.000000,19.000000,590.568333,0.003125,0.025000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
75%,3.000000,93.975000,0.000000,0.000000,38.000000,1436.318029,0.016429,0.050000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
max,26.000000,2407.423810,14.000000,1778.000000,518.000000,27009.859430,0.200000,0.200000,360.953384,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000

In [42]:

# Adjust the display setting to show all columns
pd.set_option('display.max_columns', None)

# Show the first 5 rows of the DataFrame
print(X_train.head())

   admin  admin_duration  info  info_duration  prod_related  \
0      8          732.25     0            0.0            34
1      0            0.00     0            0.0             4
2      0            0.00     0            0.0             4
3      2          338.00     0            0.0            17
4      0            0.00     0            0.0            32

   prod_related_duration  bounce_rate  exit_rate  page_value  special_day  \
0            1345.755952     0.005128   0.013342   12.274195          0.8
1             157.200000     0.040000   0.100000    0.000000          0.0
2              42.000000     0.000000   0.050000    0.000000          0.0
3            1205.566667     0.012500   0.037500   19.236250          0.8
4             827.646212     0.000000   0.000587   54.676348          0.0

   weekend  month_Aug  month_Dec  month_Feb  month_Jul  month_June  month_Mar  \
0    False        0.0        0.0        0.0        0.0         0.0        0.0
1     True        0.0        0.0        0.0        0.0         0.0        0.0
2    False        0.0        1.0        0.0        0.0         0.0        0.0
3    False        0.0        0.0        0.0        0.0         0.0        0.0
4    False        0.0        0.0        0.0        0.0         0.0        1.0

   month_May  month_Nov  month_Oct  month_Sep  visitor_type_New_Visitor  \
0        1.0        0.0        0.0        0.0                       0.0
1        0.0        0.0        1.0        0.0                       0.0
2        0.0        0.0        0.0        0.0                       0.0
3        1.0        0.0        0.0        0.0                       0.0
4        0.0        0.0        0.0        0.0                       0.0

   visitor_type_Other  visitor_type_Returning_Visitor  os_1  os_2  os_3  os_4  \
0                 0.0                             1.0   0.0   0.0   1.0   0.0
1                 0.0                             1.0   1.0   0.0   0.0   0.0
2                 0.0                             1.0   0.0   1.0   0.0   0.0
3                 0.0                             1.0   0.0   0.0   1.0   0.0
4                 0.0                             1.0   0.0   1.0   0.0   0.0

   os_5  os_6  os_7  os_8  browser_1  browser_2  browser_3  browser_4  \
0   0.0   0.0   0.0   0.0        0.0        0.0        1.0        0.0
1   0.0   0.0   0.0   0.0        0.0        0.0        0.0        0.0
2   0.0   0.0   0.0   0.0        0.0        0.0        0.0        0.0
3   0.0   0.0   0.0   0.0        0.0        1.0        0.0        0.0
4   0.0   0.0   0.0   0.0        0.0        1.0        0.0        0.0

   browser_5  browser_6  browser_7  browser_8  browser_9  browser_10  \
0        0.0        0.0        0.0        0.0        0.0         0.0
1        0.0        0.0        0.0        1.0        0.0         0.0
2        0.0        0.0        0.0        0.0        0.0         1.0
3        0.0        0.0        0.0        0.0        0.0         0.0
4        0.0        0.0        0.0        0.0        0.0         0.0

   browser_11  browser_12  browser_13  region_1  region_2  region_3  region_4  \
0         0.0         0.0         0.0       0.0       0.0       1.0       0.0
1         0.0         0.0         0.0       0.0       0.0       1.0       0.0
2         0.0         0.0         0.0       1.0       0.0       0.0       0.0
3         0.0         0.0         0.0       0.0       1.0       0.0       0.0
4         0.0         0.0         0.0       0.0       0.0       0.0       0.0

   region_5  region_6  region_7  region_8  region_9  traffic_type_1  \
0       0.0       0.0       0.0       0.0       0.0             0.0
1       0.0       0.0       0.0       0.0       0.0             1.0
2       0.0       0.0       0.0       0.0       0.0             0.0
3       0.0       0.0       0.0       0.0       0.0             0.0
4       0.0       0.0       1.0       0.0       0.0             0.0

   traffic_type_2  traffic_type_3  traffic_type_4  traffic_type_5  \
0             1.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             1.0             0.0             0.0             0.0
3             1.0             0.0             0.0             0.0
4             1.0             0.0             0.0             0.0

   traffic_type_6  traffic_type_7  traffic_type_8  traffic_type_9  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0
3             0.0             0.0             0.0             0.0
4             0.0             0.0             0.0             0.0

   traffic_type_10  traffic_type_11  traffic_type_12  traffic_type_13  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   traffic_type_14  traffic_type_15  traffic_type_16  traffic_type_17  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   traffic_type_18  traffic_type_19  traffic_type_20
0              0.0              0.0              0.0
1              0.0              0.0              0.0
2              0.0              0.0              0.0
3              0.0              0.0              0.0
4              0.0              0.0              0.0

In [43]:
y_train.head()

   revenue
0    False
1    False
2    False
3     True
4     True

## XGBoost

In [44]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in C:\Users\sboub\AppData\Roaming\Python\Python311\site-packages (3.2.0)
Requirement already satisfied: numpy in C:\Users\sboub\AppData\Roaming\Python\Python311\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in C:\Users\sboub\AppData\Roaming\Python\Python311\site-packages (from xgboost) (1.17.0)

In [45]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix

In [46]:
xgb = xgb.XGBClassifier(n_estimators=100, max_depth=5, learning_rate=0.1)

In [47]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [48]:
# Classification report

y_pred_xgb = xgb.predict(X_test)

print(classification_report(y_true=y_test, y_pred=y_pred_xgb))

              precision    recall  f1-score   support

       False       0.93      0.96      0.94      2084
        True       0.74      0.60      0.66       382

    accuracy                           0.91      2466
   macro avg       0.83      0.78      0.80      2466
weighted avg       0.90      0.91      0.90      2466

In [49]:
# Confusion matrix 
print(confusion_matrix(y_true=y_test, y_pred=y_pred_xgb))

[[2004   80]
 [ 154  228]]

# Saving plk file for deployment

The chosen model is XGBoost, so we save this in the pkl file for Streamlit

In [50]:
import pickle

In [51]:
with open ("../models/xgb_model.pkl", "wb") as f:
    pickle.dump(xgb, f)